appapi/urls.py
from django.urls import path
from .views import visa_view

app_name = "appapi"

urlpatterns = [
    # path('cities/', cities_view, name="cities"),
    path('visa/', visa_view, name="visa"),
]

appmain/urls.py
from django.urls import path
from .views import home

app_name = "appmain"

urlpatterns = [
    path('', home, name="home"),
    # path('index/', index, name="index"),
]

pjcalendar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView,LogoutView
from appmain.views import dashboard_view,settings_view, password_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',LoginView.as_view(template_name='appuser/login.html'),name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),
    path('oauth/',include('social_django.urls',namespace='social')),
    path('dashboard/',dashboard_view,name='dashboard'),
    path('settings/', settings_view, name='settings'),
    path('password/', password_view, name='password'),
    path('', include('appmain.urls')),
    path('', include('appapi.urls')),
    path('', include(('appcal.urls'))),
    # path('fb/', fb_view, name='fb')
    # path('user/',include('appuser.urls')),
]

appmain/forms.py
from django import forms
from ktag.fields import TagField
import os,json
from pjcalendar.settings import BASE_DIR
from copy import deepcopy

filepath = os.path.join(BASE_DIR, "appmain/static/appmain/countries.min.json")
with open(filepath, "r") as f:
    country_file = json.load(f)
CF = country_file


def get_country_list(CF):
    country_list = []
    for k, v in CF.items():
        country_list.append(k)
    country_list.sort(reverse=True)
    return country_list


def get_city_list(CF, country):
    city_list = []
    for k, v in CF.items():
        if k == country:
            city_list=v
    city_list.sort(reverse=True)
    return city_list


class FormCountry(forms.Form):
    country = TagField(label='Country:', delimiters=',', data_list=get_country_list(CF), initial='Canada', max_tags=1,
                       help_text="Only one is allowed for the city list.")



class FormCity(forms.Form):
    def __init__(self, *args, **kwargs):
        self.country = kwargs.pop('country')
        super(FormCity, self).__init__(*args, **kwargs)
        self.fields['city'] = TagField(label='Choose from the city list:',
                                       delimiters=',',initial='Toronto, Ottawa', data_list=get_city_list(CF, self.country),
                                       max_tags=5, help_text="Not more than 5 cities are allowed")

    city = TagField(label='Choose from the city list:',
                           delimiters=',',initial='Toronto, Ottawa',
                           max_tags=5, help_text="Not more than 5 cities are allowed")

appmain/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from .forms import FormCountry, FormCity
import json, os
from social_django.models import UserSocialAuth
from pjcalendar.settings import BASE_DIR


def home(request):
    chosen_country = ''
    chosen_city = ''
    if request.method == 'POST':
        form = FormCountry(request.POST)
        if form.is_valid():
            x=form.cleaned_data['country']
            chosen_country = x[0]

            form_city = FormCity(request.POST, country=chosen_country)
            if form_city.is_valid():
                chosen_city = form_city.cleaned_data['city']
        else:
            form_city=FormCity(country='Canada')
    else:
        form = FormCountry()
        form_city = FormCity(country='Canada')
    context = {'form': form, 'form_city': form_city, "chosen_country": chosen_country, "chosen_city": chosen_city}
    return render(request, 'appmain/home.html',context )


@login_required
def dashboard_view(request):
    return render(request, 'appmain/dashboard.html')

@login_required
def settings_view(request):
    user = request.user
    try:
        github_login = user.social_auth.get(provider='github')
    except UserSocialAuth.DoesNotExist:
        github_login = None
    try:
        twitter_login = user.social_auth.get(provider='twitter')
    except UserSocialAuth.DoesNotExist:
        twitter_login = None
    try:
        facebook_login = user.social_auth.get(provider='facebook')
    except UserSocialAuth.DoesNotExist:
        facebook_login = None
    can_disconnect = (user.social_auth.count()>1 or user.has_usable_password())
    context = {'github': github_login, 'twitter_login': twitter_login,
               'facebook_login': facebook_login, 'can_disconnect': can_disconnect}
    return render(request, 'appmain/settings.html',context)


@login_required
def password_view(request):
    if request.user.has_usable_password():
        PasswordForm = PasswordChangeForm
    else:
        PasswordForm = AdminPasswordChangeForm

    if request.method == "POST":
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('password')
        else:
            messages.error(request, 'Please correct the error below')
    else:
        form = PasswordForm(request.user)
    return render(request, 'appmain/password.html', {'form': form})

appmain/templates/appmain/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    {% load static %}
    <!--<link rel="stylesheet" href="{% static 'js/script.js' %}">-->

    <link href="{% static 'appmain/favicon.ico' %}" rel="icon" type="image/x-icon" />
    <!--<link rel="stylesheet" href="{% static 'css/tagify.css' %}" >-->

    <title>Event Builder</title>

</head>
<body>
    <head>

    <div class="jumbotron text-center" style="margin-bottom:0">
        <img src="{% static 'appmain/tts_log.png' %}" alt="tts_logo">
    </div>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <i class="fas fa-clock" style="color:white;"> </i><a class="navbar-brand" href="#">Calendar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'appmain:home' %}">Home</a>
          </li>
          <li class="nav-item">
              {% if user.is_authenticated == True %}
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'appapi:visa' %}">Visa Info</a>
          </li>
        </ul>
      </div>
    </nav>
    </head>

    <main>
    {% if messages %}
        {% for message in messages%}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor%}
    {% endif %}

    {% block title %}
    {% endblock %}

    {%block content%}
        {%endblock content%}
    </main>

    <footer>

    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    {% block javascript %} {% endblock %}

</body>
</html>

appmain/templates/appmain/dashboard.html
{% extends "appmain/base.html" %}

{% block title %}
	{{ block.super }}
{% endblock %}

{% block content %}

	<h2 class="mt-5 text-center">Welcome {{ request.user }}</h2>

{% endblock content %}

appmain/templates/appmain/fb.html
<!DOCTYPE html>
<html>
<head>
<title>Facebook Login JavaScript Example</title>
<meta charset="UTF-8">
</head>
<body>
<script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else {
      // The person is not logged into your app or we are unable to tell.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
    FB.init({
      appId      : '{TODO facebook id}',
      cookie     : true,  // enable cookies to allow the server to access
                          // the session
      xfbml      : true,  // parse social plugins on this page
      version    : '{TODO facebook api key}' // The Graph API version to use for the call
    });

    // Now that we've initialized the JavaScript SDK, we call
    // FB.getLoginStatus().  This function gets the state of the
    // person visiting this page and can return one of three states to
    // the callback you provide.  They can be:
    //
    // 1. Logged into your app ('connected')
    // 2. Logged into Facebook, but not your app ('not_authorized')
    // 3. Not logged into Facebook and can't tell if they are logged into
    //    your app or not.
    //
    // These three cases are handled in the callback function.

    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->

<fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
</fb:login-button>

<div id="status">
</div>

</body>
</html>

appmain/templates/appmain/home.html
{% extends 'appmain/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/main.css' %}" >

  <h2 class="mt-5 text-center">Welcome {{ request.user }}</h2>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
          <div class="form-group">
          <script src="{% static 'ktag/js/tagify.min.js' %}"> </script>
              <div id="box">
                 <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="OK" style="font-size: small" name="btn-country">
                </form>

              <br>

                <form action="" method="post">
                    {% csrf_token %}
                    {{ form_city.as_p }}
                    <input type="submit" value="OK" style="font-size: small" name="btn-city">
                </form>
              </div>
          </div>
    </div>
    <div class="col-md-3">
       <p>chosen country: {{ chosen_country }}</p>
       <p>chosen cities: {{ chosen_city }}</p>
    </div>
</div>
<br><br>

{% endblock %}

appmain/templates/appmain/index.html
{% extends 'appmain/base.html' %}

{% load static %}
{% block content %}

  <h2 class="mt-5 text-center">Welcome {{ request.user }}</h2>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
         <script src="{% static 'ktag/js/tagify.min.js' %}"> </script>
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}
            <br>
            <input type="submit" value="OK" style="font-size: larger">
        </form>
    </div>
    <div class="col-md-3"></div>
</div>


{% endblock %}

appmain/templates/appmain/password.html
{% extends "appmain/base.html" %}

{% block title %}
	{{ block.super }}
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <form method="post">
            {% csrf_token %}
            <p class="h4 mb-4">Change Password</p>
            {% if not user.has_usable_password %}
                <p style="color: red"> You have not defined a password yet.</p>
            {% endif %}
        {{ form.as_p }}
            <button class="btn btn-info btn-block" type="submit"> Save changes</button>
        </form>

    </div>
    <div class="col-md-3"></div>
</div>
<script>
    var ulElement = document.getElementsByTagName("li");
	ulElement.classList.add("text-left");
	console.log("script is running");
</script>
{% endblock content %}

appmain/templates/appmain/settings.html
{% extends "appmain/base.html" %}

{% block title %}
	Webapp - Settings
{% endblock %}

{% block content %}
<h2 class="text-left mt-4">Settings</h2>
<h3 class="mt-4">Github Settings</h3>

{% if github_login %}
    <p>Connected as <a href="https://github.com/{{ github_login.extra_data.login }}/" target="_blank">
    {{ github_login.extra_data.login }}</a></p>
    {% if can_disconnect %}
        <form method="post" action="{% url 'social:disconnect' 'github' %}">
            {% csrf_token %}
            <button class="btn btn-outline-danger waves-effect" type="submit">Disconnect from GitHub</button>
        </form>
    {% else %}
        <button class="btn btn-outline-danger waves-effect btn-disabled" type="submit">
            Disconnect from GitHub</button>
        <p>You must define a <a href="{% url 'password' %}">password</a> before disconnecting from GitHub</p>
    {% endif %}

{% else %}
    <a class="btn btn-outline-success waves-effect" href="{% url 'social:begin' 'github' %}">Connect to GitHub</a>
{% endif %}

<h3 class="mt-4">Twitter Settings</h3>
{% if twitter_login %}
    <p>Connected as <a href="https://twitter.com/{{ twitter_login.extra_data.access_token.screen_name }}/" target="_blank">
    {{ twitter_login.extra_data.login }}</a></p>
    {% if can_disconnect %}
        <form method="post" action="{% url 'social:disconnect' 'twitter' %}">
            {% csrf_token %}
            <button class="btn btn-outline-danger waves-effect" type="submit">Disconnect from Twitter</button>
        </form>
    {% else %}
        <button class="btn btn-outline-danger waves-effect btn-disabled" type="submit">
            Disconnect from Twitter</button>
        <p>You must define a <a href="{% url 'password' %}">password</a> before disconnecting from Twitter</p>
    {% endif %}

{% else %}
    <a class="btn btn-outline-success waves-effect" href="{% url 'social:begin' 'twitter' %}">Connect to Twitter</a>
{% endif %}

<h3 class="mt-4">Facebook Settings</h3>
{% if facebook_login %}
    <p>Connected as <a href="https://facebook.com/{{ facebook_login.extra_data.id }}/" target="_blank">
    {{ facebook_login.extra_data.login }}</a></p>
    {% if can_disconnect %}
        <form method="post" action="{% url 'social:disconnect' 'facebook' %}">
            {% csrf_token %}
            <button class="btn btn-outline-danger waves-effect" type="submit">Disconnect from Facebook</button>
        </form>
    {% else %}
        <button class="btn btn-outline-danger waves-effect btn-disabled" type="submit">
            Disconnect from Facebook</button>
        <p>You must define a <a href="{% url 'password' %}">password</a> before disconnecting from Facebook</p>
    {% endif %}

{% else %}
    <a class="btn btn-outline-success waves-effect" href="{% url 'social:begin' 'facebook' %}">Connect to Facebook</a>
{% endif %}

{% endblock content %}